마크다운모드


작성 코드 설명 및 부가적인 정보 기입이 가능한 셀

ctrl+ 엔터: 현재 셀만 실행
shift+ 엔터: 현재 셀 실행 후 아래 셀로 이동. 단 아래 쉘 없으면 자동 쉘 추가
ESC 후 M/m: Markdown
ESC 후 Y/y: code용 셀로 전환
ESC 후 A/a: above 약자 위에 셀 추가
ESC 후 B/b: below 약자 위에 셀 추가 
ESC 후

In [1]:
import pandas as pd

pd.__version__

'2.3.3'

-Dataframe/Series의 원소/요소의 실제 데이터에 맞게 타입 변환
 * 현재 타입 확인 속성 : dtype/dtypes
 * 현재 타입 변경 메서드 : 변수명.astype(변환_타입명) 반드시 저장 필수!!

In [ ]:
## 모듈 로딩
import pandas as pd             # 데이터 분석용 패키지
import numpy as np              # 배열을 파이썬 언어로 구현한 패키지
                                # pandas에서 데이터 저장을 numpy의 배열로 함!

In [3]:
## 데이터 준비 및 DF 인스턴스 생성
df = pd.DataFrame({
"이름": ["김민수", "이서연", "박지훈"],
"나이": ["20", "21", "19"],
"점수": ["85.5", "90.0", "78.5"],
"가입일": ["2024-01-10", "2024-02-15", "2024-03-01"]
})

In [4]:
## DF 인스턴스 확인
df
df.index

## 실제 데이터 일부
df.head(2)

## > 실제 데이터와 타입이 맞지 않는 컬럼 확인
## 나이 >>> int 점수 >>> float, 가입일 >> datetime64[ns]
## >> 변환 자료형 : 타입명 입력 시 가장 큰 값의 타입 (int > int64, float > float64)
df['나이'] = df['나이'].astype(int)    # object 에서 int64로 변경된다, inplace매개변수 x, 그래서 반드시 저장 
df['점수'] = df['점수'].astype(float)
df['가입일'] = df['가입일'].astype('datetime64[ns]')    # 날짜시간타입명은 반드시 문자열!!

In [5]:
## >> 변환 자료형 : 타입명 입력 시 가장 큰 값의 타입 (int > int64, float > float64)
## >> 결측치 처리 가능한 타입 : 첫글자 대문자
df['나이'] = df['나이'].astype('Int8')    # object 에서 int64로 변경된다, inplace매개변수 x, 그래서 반드시 저장
df['점수'] = df['점수'].astype('Float32')
df['가입일'] = df['가입일'].astype('datetime64[ns]')    # 날짜시간타입명은 반드시 문자열!! 권장은 X


df.dtypes

이름             object
나이               Int8
점수            Float32
가입일    datetime64[ns]
dtype: object

In [6]:
print("변환 전=====\n", df.dtypes)

변환 전=====
 이름             object
나이               Int8
점수            Float32
가입일    datetime64[ns]
dtype: object

In [7]:
## 가입일 컬럼 object >>> datetime64[ns] 형변환
pd.to_datetime(df.가입일)

0   2024-01-10
1   2024-02-15
2   2024-03-01
Name: 가입일, dtype: datetime64[ns]

In [10]:
## 데이터 준비 및 DF 인스턴스 생성
DATA_FILE='../Data/iris.csv'

# 첫번째 줄: 컬럼명 OK, 구분자: 콤마
pd.read_csv(DATA_FILE)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:



pd.get_dummies(DATA_FILE, columns=["variety"], dtype=int)

   ../Data/iris.csv
0                 1

: