#### 접근자 (Accessor) 
- Series의 원소/요소값이 특정 데이터타입인 경우 관련 메서드를 활용할 수 있도록 해주는 요소
- 종류
    * 문자형 타입  : Series.str
    * 날짜시간 타입 : Series.dt
    * 범주형 타입 : Series.cat

In [1]:
## 모듈 로딩
import pandas as pd

In [2]:
## ------------------------------------------------------
## [1] 문자형 접근자 
## ------------------------------------------------------
## SR 인스턴스 생성
nameSR = pd.Series(['Hong Gil-Dong', 'Kim Na-Na', 'Lee Min-Ho'])
display(nameSR)

0    Hong Gil-Dong
1        Kim Na-Na
2       Lee Min-Ho
dtype: object

In [3]:
## 원소를 모두 대문자로 변경하고자 할 경우
print("일반 방법------") 
for idx in range(nameSR.shape[0]):
    print(nameSR[idx].upper() )


print("\nstr 접근자 방법----")
nameSR.str.upper()

일반 방법------
HONG GIL-DONG
KIM NA-NA
LEE MIN-HO

str 접근자 방법----

0    HONG GIL-DONG
1        KIM NA-NA
2       LEE MIN-HO
dtype: object

In [4]:
## 원소내 특정 문자 존재 검사 
print("일반 방법------") 
for idx in range(nameSR.shape[0]):
    print('im' in  nameSR[idx] )


print("\nstr 접근자 방법----")
nameSR.str.contains('IM', case=False)

일반 방법------
False
True
False

str 접근자 방법----

0    False
1     True
2    False
dtype: bool

In [5]:
## 원소의 성과 이름 분리 컬럼
print("일반 방법------") 
userDF = pd.DataFrame(columns=['Last', 'First'])
for idx in range(nameSR.shape[0]):
    last, first = nameSR[idx].split()
    userDF.loc[userDF.shape[0]+1]= [last, first]
display(userDF)

print("\nstr 접근자 방법----")
nameSR.str.split(expand=True)

일반 방법------

   Last     First
1  Hong  Gil-Dong
2   Kim     Na-Na
3   Lee    Min-Ho

str 접근자 방법----

      0         1
0  Hong  Gil-Dong
1   Kim     Na-Na
2   Lee    Min-Ho

In [6]:
## ------------------------------------------------------
## [2] 날짜/시간형 접근자 
## ------------------------------------------------------
dataSR = pd.Series(["2024-01-01", "2024-01-15", "2024-02-5"], dtype="datetime64[ns]" )
dataSR

0   2024-01-01
1   2024-01-15
2   2024-02-05
dtype: datetime64[ns]

In [7]:
## 요일변환
dataSR.dt.day_name()

0    Monday
1    Monday
2    Monday
dtype: object

In [8]:
## 시간 추출, 분 추출
dataSR.dt.hour, dataSR.dt.minute

(0    0
 1    0
 2    0
 dtype: int32,
 0    0
 1    0
 2    0
 dtype: int32)

In [9]:
## ------------------------------------------------------
## [3] 카테고리 접근자 
## ------------------------------------------------------
df = pd.DataFrame({
    "이름": ["김민수", "이서연", "박지훈", "최유진", "정하늘"],
    "등급": ["A", "B", "A", "C", "B"],
    "지역": ["서울", "부산", "서울", "대구", "부산"]
})

display(df)
print(df.info())

    이름 등급  지역
0  김민수  A  서울
1  이서연  B  부산
2  박지훈  A  서울
3  최유진  C  대구
4  정하늘  B  부산

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      object
 1   등급      5 non-null      object
 2   지역      5 non-null      object
dtypes: object(3)
memory usage: 248.0+ bytes
None

In [10]:
## category 타입으로 변환
df["등급"] = df["등급"].astype("category")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      object
 1   등급      5 non-null      category
 2   지역      5 non-null      object
dtypes: category(1), object(2)
memory usage: 345.0+ bytes
None

In [13]:
## -------------------------
## cat 접근자 활용
## -------------------------
print("카테고리 목록 확인 :",   df["등급"].cat.categories)
print("카테고리 개수 확인 :",   df["등급"].cat.categories.size)
print("카테고리 코드 번호 :\n", df["등급"].cat.codes, sep='')

카테고리 목록 확인 : Index(['A', 'B', 'C'], dtype='object')
카테고리 개수 확인 : 3
카테고리 코드 번호 :
0    0
1    1
2    0
3    2
4    1
dtype: int8

In [ ]:
## => 카테고리 이름 변경
df["등급"] = df["등급"].cat.rename_categories({ "A": "우수", "B": "보통", "C": "미흡" })

print("카테고리 이름 변경 :\n", df["등급"], sep='')

카테고리 이름 변경 :
0    우수
1    보통
2    우수
3    미흡
4    보통
Name: 등급, dtype: category
Categories (3, object): ['우수', '보통', '미흡']

In [15]:
## => 새 카테고리 추가
df["등급"] = df["등급"].cat.add_categories(["매우우수"])

print("새 카테고리 추가 :\n", df["등급"], sep='')

새 카테고리 추가 :
0    우수
1    보통
2    우수
3    미흡
4    보통
Name: 등급, dtype: category
Categories (4, object): ['우수', '보통', '미흡', '매우우수']