### 【 PANDAS 실습 문제 】

- 날짜: 2026년 05월 01일
- 사용 파일: 시도별 전출입 인구수.xlsx

#### 준비 0) 모듈 및 데이터 설정

In [1]:
## 모듈 로딩
import pandas as pd

In [2]:
## 데이터 준비
DATA_FILE = '../DATA/시도별 전출입 인구수.xlsx'

---
#### 문제 1) 데이터 파일을 읽고 기본 구조를 확인하세요.
[요구사항]
1. "시도별 전출입 인구수.xlsx" 파일의 "데이터" 시트를 읽어 DataFrame으로 저장하세요.
2. 앞부분 5개 행을 출력하세요.
3. 데이터의 행수와 열수를 출력하세요.
4. 각 컬럼의 자료형을 확인하세요.
---

In [3]:
## xlsx ==> DataFrame으로 로딩
df = pd.read_excel(DATA_FILE, sheet_name="데이터")

In [4]:
## 2. 앞부분 5개 행을 출력하세요.
print("[앞부분 5개 행]")
df.head()

[앞부분 5개 행]

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [5]:
## 3. 데이터의 행수와 열수를 출력하세요.
print(f"[행/열 개수]  {df.shape}")
print(f"행 : {df.shape[0]}개")
print(f"열 : {df.shape[1]}개")

[행/열 개수]  (325, 50)
행 : 325개
열 : 50개

In [6]:
## 4.각 컬럼의 자료형을 확인하세요.
print(f"[컬럼별 자료형]")
df.dtypes

[컬럼별 자료형]

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [7]:
### 데이터 전처리 진행 체크
# 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
# 2. 0번행 의미 없는 행 => 삭제
# 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제

---
#### 문제 2) 불필요한 행을 삭제하고 인덱스를 초기화하세요
[요구사항]
1. 데이터 파일을 읽은 후, 두 번째 행에 들어 있는 "이동자수 (명)" 설명 행을 삭제하세요.
2. 삭제 후 reset_index()를 사용하여 행 인덱스를 0부터 다시 설정하세요.
3. 처리 전과 처리 후의 shape를 각각 출력하세요.
4. 처리 후 앞부분 5개 행을 출력하세요.
---

In [8]:
## 1. 데이터 파일을 읽은 후, 두 번째 행에 들어 있는 "이동자수 (명)" 설명 행을 삭제하세요.
df2 = df.drop(index=0)
df2.head(3)

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073

In [9]:
##2. 삭제 후 reset_index()를 사용하여 행 인덱스를 0부터 다시 설정하세요.
df2 = df2.reset_index(drop=True)

In [10]:
##3. 처리 전과 처리 후의 shape를 각각 출력하세요.
print("[처리 전 shape]", df.shape, "===>", "[처리 후 shape]", df2.shape)

[처리 전 shape] (325, 50) ===> [처리 후 shape] (324, 50)

In [11]:
## 4. 처리 후 앞부분 5개 행을 출력하세요.
df2.head(3)

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
1,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
2,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073