### [ 주제: 붓꽃의 품종 분류 ] <hr>

- 학습 종류: 지도 학습
- 학습 방법: 분류 관련 모델 중에서 선택
- 데이터: iris.csv
- 구현 단계
    * (1) 데이터 준비 및 확인
    * (2) 데이터 전처리
    * (3) 학습/ 검증/ 테스트용 데이터셋 분리
    * (4) 학습 => 교차검증+ 하이퍼파라미터 튜닝
    * (5) 평가

- **[0] 모듈 로딩**

In [5]:
## -------------------------------------
## 이미지 데이터 로딩 & 기본 정보
## -------------------------------------
import cv2
import os
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import numpy as np
import matplotlib.cm as cm
import sys
sys.path.append(r"C:\KDT14\7_CV")

import importlib
import cv_utils

importlib.reload(cv_utils)

from sklearn.model_selection import train_test_split #학습용| 테스트용 데이터 분할
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier # 모델클래스
from sklearn.metrics import accuracy_score, classification_report # 평가
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

- **[1] 데이터 준비 및 확인**

In [6]:
DATA_FILE= './iris.csv'

dataDF= pd.read_csv(DATA_FILE)

In [7]:
## 데이터 기본 정보 확인=> 형태, 컬럼(타입, 결측치 여부, 개수), 실제 데이터와 비교, 컬럼별 통계치
dataDF.info()
display(dataDF.head(3))
dataDF.describe() # 통계치
dataDF.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa

        sepal.length  sepal.width  petal.length  petal.width variety
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  Setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [8]:
## [ 1차 해석 ]
## - variety 컬럼: str==> category 형변환
## - 결측치: 없음
## - 타겟/ 라벨/ 클래스 컬럼: variety
## - 피쳐/ 특성/ 속성 컬럼: sepal/length, sepal.width, petal.length, petal.width

- **[2]데이터 전처리**

In [9]:
## variety 컬럼 : str == > category 형변환
## - df.astype으로 자료형 변환: inplace 매개변수x. 반드시 저장

dataDF.variety= dataDF.variety.astype('category')

display(dataDF.dtypes)

sepal.length     float64
sepal.width      float64
petal.length     float64
petal.width      float64
variety         category
dtype: object

- **[3]학습용/ 검증용/ 테스트용 데이터셋 준비**

In [10]:
## 피처와 타겟 분리
featureDF= dataDF[dataDF.columns[:-1]]
targetSR= dataDF[dataDF.columns[-1]]

print(f'피처: {featureDF.shape}, 타겟: {targetSR.shape}')

피처: (150, 4), 타겟: (150,)

In [11]:
## => 학습용 |테스트용 분리 : 분류 => 타겟 클래스 비율 유지 stratify 매개변수 설정
#                          재현성 => random_state 매개변수 설정
#                          피처 차원-> 2차원
#                          타겟 차원-> 1차원



X_train, X_test, y_train, y_test= train_test_split(featureDF, targetSR, test_size=0.2, random_state= 10, stratify= targetSR)

In [12]:
## => 확인
print(f'학습용 : {X_train.shape}, {y_train.shape} 테스트용 : {X_test.shape}, {y_test.shape}')
print(f'클래스 데이터 구성\n', y_train.value_counts().tolist())
print(f'\n테스트 데이터 구성\n', y_test.value_counts().tolist())

학습용 : (120, 4), (120,) 테스트용 : (30, 4), (30,)
클래스 데이터 구성
 [40, 40, 40]

테스트 데이터 구성
 [10, 10, 10]

- **[4] 교차검증+ 튜닝**

In [13]:
## ------------------------------------------
## => GridSearchCV 인스턴스 생성 및 진행
## - 모든 조합의 모델 생성
## - 조합된 모델별 교차 검증 진행
## - 최적 조합의 하이퍼파라미터 추출
## - 단점 : 시간이 오래 걸림 !!!
## ------------------------------------------
## => 모델인스턴스 : KNN
kModel = KNeighborsClassifier()

## => 모델의 하이퍼파라미터 Dict
param_dict ={'n_neighbors' : range(1,51,2),
'p': [1,2],
'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}

StratifiedKFold(shuffle=True, random_state= 10)

## => 튜닝 및 교차검증 진행 인스턴스
gsModel = GridSearchCV(kModel, param_grid=param_dict, return_train_score=True)

In [14]:
## 하이퍼파라미터 조합으로 모델 생성 및 교차검증 학습 진행
## => Y_TRAIN에 따라서 KFold, StatifiedFold로 선택됨
gsModel.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': range(1, 51, 2), 'p': [1, 2]},
             return_train_score=True)

In [15]:
## 학습 후 설정된 모델 파라미터 확인
gsModel.cv_results_

{'mean_fit_time': array([0.00134926, 0.00140781, 0.0016068 , 0.00160799, 0.00191665,
        0.00231447, 0.00161433, 0.00100327, 0.00170455, 0.00160728,
        0.00181041, 0.00172567, 0.00187683, 0.00140634, 0.00160637,
        0.00130506, 0.00180531, 0.00202274, 0.00091481, 0.00201621,
        0.00120945, 0.00151501, 0.00130463, 0.00212097, 0.0016633 ,
        0.00137634, 0.00150714, 0.00150828, 0.00171251, 0.00160718,
        0.00170584, 0.00183358, 0.00140433, 0.00181017, 0.001407  ,
        0.00158911, 0.0016892 , 0.00147328, 0.00125661, 0.00130272,
        0.00169029, 0.00130091, 0.00151224, 0.00150657, 0.00127316,
        0.0015192 , 0.00130596, 0.00150876, 0.00123963, 0.00141959,
        0.00171247, 0.00115643, 0.00143299, 0.00110893, 0.00169334,
        0.00159554, 0.00160346, 0.0014308 , 0.00131607, 0.00171456,
        0.00181208, 0.00127854, 0.0016089 , 0.00221257, 0.00150046,
        0.00132208, 0.00170808, 0.00160408, 0.00128665, 0.00164371,
        0.00100856, 0.0014421 , 0.00154638, 0.00150671, 0.0016932 ,
        0.00169015, 0.00194058, 0.00165806, 0.00150213, 0.00170741,
        0.00162082, 0.00161352, 0.00122709, 0.00130219, 0.00100503,
        0.00160294, 0.00180664, 0.00210671, 0.00130486, 0.00200381,
        0.0020133 , 0.00140567, 0.00162549, 0.00133266, 0.00168557,
        0.00161252, 0.00141754, 0.0015059 , 0.00234451, 0.00194874,
        0.00238285, 0.00170703, 0.00180483, 0.00120192, 0.00110621,
        0.001509  , 0.00222387, 0.00170598, 0.00216599, 0.00151997,
        0.00140471, 0.00151806, 0.00142403, 0.00153594, 0.00224428,
        0.0012074 , 0.00101061, 0.00151291, 0.00152712, 0.00152493,
        0.0015069 , 0.00160913, 0.0010047 , 0.00131745, 0.00180774,
        0.00132084, 0.00188494, 0.00170684, 0.00149279, 0.00177236,
        0.00162506, 0.00140924, 0.00145445, 0.00130873, 0.00203004,
        0.0025351 , 0.00211015, 0.00155149, 0.00140653, 0.0019691 ,
        0.0020381 , 0.00153241, 0.00190964, 0.00162292, 0.00170274,
        0.00140362, 0.00174432, 0.00191207, 0.00151019, 0.00171971,
        0.00175843, 0.00180879, 0.00127692, 0.0018146 , 0.00122352,
        0.00160751, 0.00120783, 0.00141587, 0.00144672, 0.00179701,
        0.00111761, 0.00155892, 0.00127077, 0.00173464, 0.0014143 ,
        0.00151691, 0.00143628, 0.00090256, 0.0018415 , 0.00200706,
        0.0016026 , 0.00147552, 0.0014504 , 0.00191751, 0.00177965,
        0.00170121, 0.00133133, 0.00150676, 0.0015842 , 0.00119796,
        0.00123768, 0.00120807, 0.00150604, 0.00151267, 0.00181541,
        0.00131307, 0.00152712, 0.00173206, 0.00161662, 0.00176973,
        0.00182366, 0.00172095, 0.00089521, 0.00080605, 0.00130854,
        0.00149183, 0.00150828, 0.00160193, 0.00100498, 0.001406  ]),
 'std_fit_time': array([5.47261613e-04, 8.64445818e-04, 3.72942344e-04, 4.96772206e-04,
        6.80732216e-04, 3.92981391e-04, 5.93089724e-04, 6.34983277e-04,
        4.02430295e-04, 5.87472176e-04, 5.12093440e-04, 5.47888862e-04,
        4.76954041e-04, 3.71404499e-04, 5.89016322e-04, 6.02437760e-04,
        8.03884815e-04, 7.27179199e-04, 1.71769625e-04, 5.54733680e-04,
        2.50613852e-04, 3.13454868e-04, 4.06021142e-04, 4.90491190e-04,
        5.49898456e-04, 5.94001589e-04, 4.45211535e-04, 4.55463047e-04,
        2.41479320e-04, 3.72342471e-04, 5.14326059e-04, 2.07786496e-04,
        3.77811095e-04, 5.12553736e-04, 3.83778873e-04, 6.03922523e-04,
        3.83419864e-04, 3.49072894e-04, 2.42737776e-04, 3.99190572e-04,
        5.54937148e-04, 6.08883403e-04, 4.58784564e-04, 6.32867718e-04,
        3.75915595e-04, 4.54182950e-04, 3.99267475e-04, 3.18967613e-04,
        4.66954863e-04, 6.64618009e-04, 4.01967236e-04, 2.77640932e-04,
        3.84307516e-04, 6.63810339e-04, 4.01050995e-04, 8.10992233e-04,
        7.34341742e-04, 5.24000091e-04, 7.59852856e-04, 4.00535538e-04,
        6.84905872e-04, 3.95841955e-04, 3.73299527e-04, 2.54954506e-04,
        4.44331095e-04, 4.32672100e-04, 6.00850721e-04, 4.91488645e-04,
        2.27014484e-04, 6.89275830e-04, 5.48134632e-06, 4.32130149e-04,
        4.02936964e-04, 4.43255922e-04, 3.82305820e-04, 5.78838418e-04,
        5.05034544e-04, 3.69939554e-04, 6.37124370e-04, 6.04188067e-04,
        6.06297676e-04, 3.75991424e-04, 2.06188512e-04, 3.99933942e-04,
        3.19514081e-04, 3.74369265e-04, 6.78211654e-04, 2.03972265e-04,
        4.02976631e-04, 2.69085744e-04, 7.21430520e-04, 4.86826649e-04,
        3.96226556e-04, 4.40705728e-04, 5.39804566e-04, 8.09129834e-04,
        5.09396716e-04, 6.34263193e-04, 3.68468539e-04, 2.37211203e-04,
        5.15066282e-04, 3.98496879e-04, 5.13747041e-04, 2.43565900e-04,
        4.90779729e-04, 4.54843200e-04, 5.30761925e-04, 3.97720455e-04,
        5.90799476e-04, 6.91658230e-04, 3.73533954e-04, 3.19776875e-04,
        4.74242983e-04, 6.76416365e-04, 1.04317987e-03, 2.45550136e-04,
        3.06831480e-04, 6.31206055e-04, 3.28102650e-04, 3.48250568e-04,
        5.76267690e-04, 5.90191223e-04, 5.50173651e-04, 8.86296155e-04,
        5.46942892e-04, 3.93083134e-04, 2.07402568e-04, 6.00867326e-04,
        3.22786651e-04, 6.18489345e-04, 4.90681539e-04, 3.77279466e-04,
        4.62100196e-04, 2.51311613e-04, 6.21229309e-04, 6.22055904e-04,
        7.35661666e-04, 4.36678102e-04, 4.96192096e-04, 2.64715537e-04,
        6.71286901e-04, 4.82336816e-04, 1.11784719e-03, 5.07596414e-04,
        4.03287304e-04, 3.75281186e-04, 4.31761641e-04, 6.72133908e-04,
        4.47236153e-04, 4.06171280e-04, 3.58146089e-04, 5.12030765e-04,
        2.25520909e-04, 4.05028693e-04, 3.83161590e-04, 3.75001203e-04,
        2.53542572e-04, 4.02827775e-04, 3.31057191e-04, 2.32039877e-04,
        4.72211493e-04, 4.63696361e-04, 2.35887202e-04, 7.49367862e-04,
        3.74256512e-04, 7.10259833e-04, 5.73206926e-04, 4.91479753e-04,
        4.24869518e-04, 3.20033705e-04, 3.74388639e-04, 4.68496898e-04,
        5.47458330e-04, 2.02137430e-04, 4.29964639e-04, 6.00523473e-04,
        5.36038205e-04, 4.49958268e-04, 4.85775935e-04, 4.06014467e-04,
        4.09171029e-04, 2.50797806e-04, 4.47460402e-04, 3.06658963e-04,
        5.14816738e-04, 2.48985425e-04, 4.77596951e-04, 8.86849962e-04,
        5.03384695e-04, 3.04980715e-04, 4.11726590e-04, 5.05586313e-04,
        3.67725779e-04, 4.03030636e-04, 4.02103055e-04, 4.65095813e-04,
        4.47178726e-04, 4.90770732e-04, 3.16236067e-04, 3.69612547e-04]),
 'mean_score_time': array([0.0025486 , 0.00207081, 0.00201564, 0.00236735, 0.00212512,
        0.00208645, 0.0018775 , 0.00256486, 0.00232148, 0.00272713,
        0.0019125 , 0.00241117, 0.00215259, 0.00191565, 0.00191288,
        0.00211382, 0.00188828, 0.00210333, 0.00281386, 0.00221334,
        0.00210466, 0.00211434, 0.00236797, 0.00211806, 0.00191045,
        0.00252776, 0.00297976, 0.0025188 , 0.0022068 , 0.00211015,
        0.00231261, 0.00226965, 0.00248585, 0.00241566, 0.00257998,
        0.00254121, 0.00219374, 0.00263066, 0.00238776, 0.0023241 ,
        0.0029191 , 0.00222507, 0.00231442, 0.00232692, 0.0021266 ,
        0.00207248, 0.00261283, 0.00191159, 0.45777068, 0.01174874,
        0.00170369, 0.00209932, 0.00210533, 0.00230494, 0.00222487,
        0.0028017 , 0.00217142, 0.00209327, 0.0019104 , 0.00253129,
        0.00220895, 0.00207725, 0.00205274, 0.00201364, 0.00248489,
        0.00267258, 0.00209031, 0.00230889, 0.00247483, 0.00173349,
        0.00251203, 0.0025022 , 0.00237279, 0.00203199, 0.00241628,
        0.00221052, 0.00220776, 0.00251136, 0.00253258, 0.002244  ,
        0.00242062, 0.00240698, 0.00271993, 0.00247402, 0.00271068,
        0.00261364, 0.00266118, 0.00259786, 0.00283275, 0.00252094,
        0.00253892, 0.00263367, 0.00259891, 0.00281591, 0.00264707,
        0.00301819, 0.00279956, 0.0030231 , 0.00281086, 0.00253639,
        0.00291286, 0.0026813 , 0.00216265, 0.00241299, 0.00251589,
        0.002314  , 0.0027072 , 0.00237241, 0.00217915, 0.00212216,
        0.00211368, 0.00211916, 0.00249877, 0.00230703, 0.00215101,
        0.0020143 , 0.00222225, 0.00251179, 0.00218854, 0.00238438,
        0.00250006, 0.00200715, 0.00231404, 0.00258303, 0.00221176,
        0.00227036, 0.00240588, 0.00241446, 0.00230598, 0.00190916,
        0.00205822, 0.00221295, 0.00271454, 0.00190558, 0.00219984,
        0.00272002, 0.00309372, 0.00241442, 0.00278125, 0.00275521,
        0.00242777, 0.00239763, 0.00261726, 0.00238395, 0.00281816,
        0.00241537, 0.00259986, 0.00263896, 0.00320864, 0.00243945,
        0.00629835, 0.0110261 , 0.00647988, 0.01083541, 0.00622616,
        0.01180105, 0.00581617, 0.0109436 , 0.00595775, 0.01120563,
        0.00672474, 0.01116872, 0.00651875, 0.01071987, 0.00552764,
        0.01036506, 0.00607419, 0.01126719, 0.00602627, 0.00973806,
        0.00537891, 0.01020927, 0.0052773 , 0.01041045, 0.00572157,
        0.01094832, 0.00673714, 0.01132269, 0.0062995 , 0.01054616,
        0.00600076, 0.01034298, 0.00573182, 0.01062489, 0.00601854,
        0.01055903, 0.00563097, 0.01054506, 0.00580788, 0.0106854 ,
        0.00534844, 0.01040902, 0.00625505, 0.01068964, 0.00621862,
        0.0100318 , 0.00629959, 0.01082816, 0.0067615 , 0.01049223]),
 'std_score_time': array([6.40594539e-04, 6.69774655e-04, 3.23844559e-04, 6.79709025e-04,
        7.11843930e-04, 4.46836196e-04, 1.93022680e-04, 6.89014339e-04,
        3.95191176e-04, 6.81725242e-04, 5.80198098e-04, 3.68874347e-04,
        7.51827026e-04, 5.94571413e-04, 3.70922838e-04, 3.73298876e-04,
        4.93834993e-04, 6.64186116e-04, 2.45466089e-04, 2.55631089e-04,
        2.01630106e-04, 4.91721552e-04, 5.67395285e-04, 3.81598791e-04,
        3.76383521e-04, 3.14761664e-04, 6.85749065e-04, 4.55042944e-04,
        2.49106550e-04, 2.02653189e-04, 4.01848624e-04, 3.22866880e-04,
        2.77693135e-04, 5.90321224e-04, 5.73634535e-04, 5.61671964e-04,
        4.82176956e-04, 5.46400340e-04, 3.89274915e-04, 2.36091655e-04,
        8.67281860e-04, 6.93269551e-04, 5.03408634e-04, 4.03914073e-04,
        4.88275257e-04, 1.24176178e-04, 3.77027153e-04, 1.99137805e-04,
        9.03115806e-01, 1.21018153e-03, 4.03012865e-04, 4.91023637e-04,
        4.62090749e-04, 5.60666473e-04, 2.47396307e-04, 4.12295434e-04,
        1.78700704e-04, 4.55834710e-04, 4.98332186e-04, 5.10408240e-04,
        4.62119936e-04, 2.25782349e-04, 3.18048862e-04, 5.54666636e-04,
        3.73002453e-04, 5.53318140e-04, 1.40965565e-04, 3.94635958e-04,
        3.21414116e-04, 5.73544808e-04, 3.17555268e-04, 4.69257843e-04,
        6.80369187e-04, 5.76337066e-04, 3.75570689e-04, 4.03472109e-04,
        5.08185899e-04, 5.51522679e-04, 6.59537098e-04, 3.79343635e-04,
        3.88630984e-04, 3.78388616e-04, 4.98895771e-04, 5.68678750e-04,
        5.17689601e-04, 6.63811936e-04, 6.64307264e-04, 5.01505338e-04,
        4.97425101e-04, 4.70626719e-04, 5.79467084e-04, 4.00340012e-04,
        3.88366890e-04, 4.13234779e-04, 6.20187588e-04, 5.39073178e-04,
        2.49401533e-04, 2.98910400e-04, 2.36310200e-04, 3.91527666e-04,
        8.65110855e-04, 5.36514116e-04, 2.02016912e-04, 3.69055400e-04,
        4.36990847e-04, 6.74591365e-04, 6.81349467e-04, 3.17646554e-04,
        3.71915102e-04, 7.58644532e-04, 5.02864080e-04, 1.94516518e-04,
        7.80334293e-04, 2.49131859e-04, 4.80019891e-04, 7.05345006e-04,
        5.20233785e-04, 4.58770638e-04, 4.11574932e-04, 8.38641877e-04,
        7.07464010e-04, 3.19653920e-04, 6.09957363e-04, 2.23877610e-04,
        2.98040748e-04, 4.89178909e-04, 4.10777430e-04, 4.90495640e-04,
        5.04509150e-04, 1.98100424e-04, 3.73935912e-04, 5.11097311e-04,
        6.15980995e-04, 1.99044681e-04, 1.88866970e-04, 7.37046851e-04,
        5.51573661e-04, 3.62516854e-04, 6.88394178e-04, 4.39361996e-04,
        8.03333780e-04, 2.02436867e-04, 7.40210028e-04, 3.79065417e-04,
        4.01708220e-04, 2.14655830e-04, 3.63098944e-04, 3.87600439e-04,
        9.84190069e-04, 4.12883006e-04, 5.05944884e-04, 4.07917353e-04,
        5.33383011e-04, 4.45465933e-04, 6.86702123e-04, 1.04835029e-03,
        3.85533101e-04, 9.65635398e-04, 9.04508402e-04, 7.57170224e-04,
        2.52087242e-04, 7.83753319e-04, 5.75355054e-04, 3.72827524e-04,
        7.25790776e-04, 6.08146798e-04, 4.83342499e-04, 4.28020545e-04,
        5.40048512e-04, 6.06041168e-04, 4.49255549e-04, 1.91051185e-04,
        5.06104829e-04, 4.71724341e-04, 5.27315131e-04, 4.76723481e-04,
        4.10271605e-04, 4.67376177e-04, 6.06374280e-04, 7.08838691e-04,
        7.54156867e-04, 6.19837495e-04, 4.94922837e-04, 4.79855047e-04,
        3.09914023e-04, 5.80276701e-04, 1.93038500e-04, 9.11484118e-04,
        2.42175214e-04, 4.14707072e-04, 6.40773926e-04, 7.37906552e-04,
        3.78797668e-04, 4.48753818e-04, 8.17862781e-04, 5.20874584e-04,
        2.65934379e-04, 7.97604470e-04, 6.26219574e-04, 5.49269830e-04]),
 'param_algorithm': masked_array(data=['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[1, 1, 3, 3, 5, 5, 7, 7, 9, 9, 11, 11, 13, 13, 15, 15,
                    17, 17, 19, 19, 21, 21, 23, 23, 25, 25, 27, 27, 29, 29,
                    31, 31, 33, 33, 35, 35, 37, 37, 39, 39, 41, 41, 43, 43,
                    45, 45, 47, 47, 49, 49, 1, 1, 3, 3, 5, 5, 7, 7, 9, 9,
                    11, 11, 13, 13, 15, 15, 17, 17, 19, 19, 21, 21, 23, 23,
                    25, 25, 27, 27, 29, 29, 31, 31, 33, 33, 35, 35, 37, 37,
                    39, 39, 41, 41, 43, 43, 45, 45, 47, 47, 49, 49, 1, 1,
                    3, 3, 5, 5, 7, 7, 9, 9, 11, 11, 13, 13, 15, 15, 17, 17,
                    19, 19, 21, 21, 23, 23, 25, 25, 27, 27, 29, 29, 31, 31,
                    33, 33, 35, 35, 37, 37, 39, 39, 41, 41, 43, 43, 45, 45,
                    47, 47, 49, 49, 1, 1, 3, 3, 5, 5, 7, 7, 9, 9, 11, 11,
                    13, 13, 15, 15, 17, 17, 19, 19, 21, 21, 23, 23, 25, 25,
                    27, 27, 29, 29, 31, 31, 33, 33, 35, 35, 37, 37, 39, 39,
                    41, 41, 43, 43, 45, 45, 47, 47, 49, 49],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,

In [16]:
## => 학습 후 설정된 모델 파라미터 확인
## - cv_results_ : 각 모델의 교차검증 결과 저장 dict 형식
cv_resultDF = pd.DataFrame(gsModel.cv_results_)

## - best_params_ : 최고 성능의 하이퍼파라미터 조합
print(f'gsModel.best_params _: {gsModel.best_params_}=> {gsModel.best_score_:.4f}')

bestModel= gsModel.best_estimator_

gsModel.best_params _: {'algorithm': 'auto', 'n_neighbors': 15, 'p': 1}=> 0.9667

- **[5] 시각화**

In [17]:

## => 모델 조합별 교차검증 결과
cv_resultDF.info()

# select_cols = [ 'param_algorithm', 'param_n_neighbors', 'param_p',
# 'split0_test_score', 'split1_test_score', 'split2_test_score',
# 'split3_test_score', 'split4_test_score', 'mean_test_score',
# 'std_test_score', 'rank_test_score']

# cv_resultDF[select_cols].head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   mean_fit_time       200 non-null    float64
 1   std_fit_time        200 non-null    float64
 2   mean_score_time     200 non-null    float64
 3   std_score_time      200 non-null    float64
 4   param_algorithm     200 non-null    object
 5   param_n_neighbors   200 non-null    int64
 6   param_p             200 non-null    int64
 7   params              200 non-null    object
 8   split0_test_score   200 non-null    float64
 9   split1_test_score   200 non-null    float64
 10  split2_test_score   200 non-null    float64
 11  split3_test_score   200 non-null    float64
 12  split4_test_score   200 non-null    float64
 13  mean_test_score     200 non-null    float64
 14  std_test_score      200 non-null    float64
 15  rank_test_score     200 non-null    int32
 16  split0_train_score  200 non-null    float64
 17  split1_train_score  200 non-null    float64
 18  split2_train_score  200 non-null    float64
 19  split3_train_score  200 non-null    float64
 20  split4_train_score  200 non-null    float64
 21  mean_train_score    200 non-null    float64
 22  std_train_score     200 non-null    float64
dtypes: float64(18), int32(1), int64(2), object(2)
memory usage: 35.3+ KB

In [18]:

## => 모델 조합별 교차검증 결과
cv_resultDF.info()

## => 확인하고 싶은 컬럼만 선택
cols =['rank_test_score', 'param_algorithm', 'param_n_neighbors', 'param_p', 'mean_test_score']

display(cv_resultDF[cols])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   mean_fit_time       200 non-null    float64
 1   std_fit_time        200 non-null    float64
 2   mean_score_time     200 non-null    float64
 3   std_score_time      200 non-null    float64
 4   param_algorithm     200 non-null    object
 5   param_n_neighbors   200 non-null    int64
 6   param_p             200 non-null    int64
 7   params              200 non-null    object
 8   split0_test_score   200 non-null    float64
 9   split1_test_score   200 non-null    float64
 10  split2_test_score   200 non-null    float64
 11  split3_test_score   200 non-null    float64
 12  split4_test_score   200 non-null    float64
 13  mean_test_score     200 non-null    float64
 14  std_test_score      200 non-null    float64
 15  rank_test_score     200 non-null    int32
 16  split0_train_score  200 non-null    float64
 17  split1_train_score  200 non-null    float64
 18  split2_train_score  200 non-null    float64
 19  split3_train_score  200 non-null    float64
 20  split4_train_score  200 non-null    float64
 21  mean_train_score    200 non-null    float64
 22  std_train_score     200 non-null    float64
dtypes: float64(18), int32(1), int64(2), object(2)
memory usage: 35.3+ KB

,rank_test_score,param_algorithm,param_n_neighbors,param_p,mean_test_score
0,29,auto,1,1,0.950000
1,29,auto,1,2,0.950000
2,62,auto,3,1,0.941667
3,62,auto,3,2,0.941667
4,85,auto,5,1,0.933333
...,...,...,...,...,...
195,143,brute,45,2,0.908333
196,182,brute,47,1,0.900000
197,143,brute,47,2,0.908333
198,143,brute,49,1,0.908333
199,143,brute,49,2,0.908333

In [19]:
param_dict ={'n_neighbors' : range(1,51,2), 'p':[1,2], 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}

## => 튜닝 및 교차검증 진행 인스턴스
gsModel = GridSearchCV(kModel, param_grid=param_dict, return_train_score=True)

In [20]:
gsModel.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': range(1, 51, 2), 'p': [1, 2]},
             return_train_score=True)

In [21]:
cv_resultDF.info()

cols =['rank_test_score', 'param_algorithm', 'param_n_neighbors', 'param_p', 'mean_test_score']

selDF= cv_resultDF[cols]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   mean_fit_time       200 non-null    float64
 1   std_fit_time        200 non-null    float64
 2   mean_score_time     200 non-null    float64
 3   std_score_time      200 non-null    float64
 4   param_algorithm     200 non-null    object
 5   param_n_neighbors   200 non-null    int64
 6   param_p             200 non-null    int64
 7   params              200 non-null    object
 8   split0_test_score   200 non-null    float64
 9   split1_test_score   200 non-null    float64
 10  split2_test_score   200 non-null    float64
 11  split3_test_score   200 non-null    float64
 12  split4_test_score   200 non-null    float64
 13  mean_test_score     200 non-null    float64
 14  std_test_score      200 non-null    float64
 15  rank_test_score     200 non-null    int32
 16  split0_train_score  200 non-null    float64
 17  split1_train_score  200 non-null    float64
 18  split2_train_score  200 non-null    float64
 19  split3_train_score  200 non-null    float64
 20  split4_train_score  200 non-null    float64
 21  mean_train_score    200 non-null    float64
 22  std_train_score     200 non-null    float64
dtypes: float64(18), int32(1), int64(2), object(2)
memory usage: 35.3+ KB

In [22]:
selDF.sort_values(by= ['rank_test_score'])
cv_resultDF.iloc[14]

mean_fit_time                                                 0.001606
std_fit_time                                                  0.000589
mean_score_time                                               0.001913
std_score_time                                                0.000371
param_algorithm                                                   auto
param_n_neighbors                                                   15
param_p                                                              1
params                {'algorithm': 'auto', 'n_neighbors': 15, 'p': 1}
split0_test_score                                             0.958333
split1_test_score                                             0.916667
split2_test_score                                                  1.0
split3_test_score                                             0.958333
split4_test_score                                                  1.0
mean_test_score                                               0.966667
std_test_score                                                 0.03118
rank_test_score                                                      1
split0_train_score                                              0.9375
split1_train_score                                            0.979167
split2_train_score                                            0.958333
split3_train_score                                             0.96875
split4_train_score                                            0.958333
mean_train_score                                              0.960417
std_train_score                                               0.013819
Name: 14, dtype: object

In [23]:
## ------------------------------------------
## => RandomizedSearchCV 인스턴스 생성 및 진행
## - GridSearchCV 보다 빠르지만 성능이 안 좋을수도 있음
## - 지정된 개수 만큼의 모델을 조합 => 속도 빠름
## - 조합된 모델별 교차 검증 진행
## - 단점 : GridSearchCV보다 최적의 조합 아닐 수 도 있음
## cv 파라미터
##   * 기본값 : 5
##   * 학습 시 전달하는 y값에 따라서 KFold, StratifiedKFold 설정
## - random_state 파라미터
##   * 재현성 위해서 설정
## - n_iter 파라미터
##   * 무작위 조합할 모델 개수 설정
## ------------------------------------------


## => 교차검증 인스턴스 생성
skFold = StratifiedKFold(n_splits=5, shuffle=True, random_state=10)

## => 튜닝 및 교차검증 진행 인스턴스
rsModel = RandomizedSearchCV(kModel, param_distributions=param_dict, cv=skFold, n_iter=50, random_state= 10, return_train_score=True)

In [24]:
## 교차검증 진행
rsModel.fit(X_train, y_train)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=10, shuffle=True),
                   estimator=KNeighborsClassifier(), n_iter=50,
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'n_neighbors': range(1, 51, 2),
                                        'p': [1, 2]},
                   random_state=10, return_train_score=True)

In [25]:
print(f'최고조합: {rsModel.best_params_} , 최고점수: {rsModel.best_score_}')

## 최고 조합으로 재학습된 모델 인스턴스
rs_best_model= rsModel.best_estimator_

## 조합 모델 별 학습 성능
cv_resultDF= pd.DataFrame(rsModel.cv_results_)
cv_resultDF.info()

최고조합: {'p': 2, 'n_neighbors': 9, 'algorithm': 'brute'} , 최고점수: 0.9583333333333334
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   mean_fit_time       50 non-null     float64
 1   std_fit_time        50 non-null     float64
 2   mean_score_time     50 non-null     float64
 3   std_score_time      50 non-null     float64
 4   param_p             50 non-null     int64
 5   param_n_neighbors   50 non-null     int64
 6   param_algorithm     50 non-null     object
 7   params              50 non-null     object
 8   split0_test_score   50 non-null     float64
 9   split1_test_score   50 non-null     float64
 10  split2_test_score   50 non-null     float64
 11  split3_test_score   50 non-null     float64
 12  split4_test_score   50 non-null     float64
 13  mean_test_score     50 non-null     float64
 14  std_test_score      50 non-null     float64
 15  rank_test_score     50 non-null     int32
 16  split0_train_score  50 non-null     float64
 17  split1_train_score  50 non-null     float64
 18  split2_train_score  50 non-null     float64
 19  split3_train_score  50 non-null     float64
 20  split4_train_score  50 non-null     float64
 21  mean_train_score    50 non-null     float64
 22  std_train_score     50 non-null     float64
dtypes: float64(18), int32(1), int64(2), object(2)
memory usage: 8.9+ KB

### [ 과제 ] <hr>

In [29]:
## 사용자로부터 입력받은 값 예측
in_data = input("붓꽃 정보 입력(예: 0.12 0.08 1.23 1.44):").split(" ")
newDF = pd.DataFrame([in_data], columns=X_train.columns)
print(newDF)


gs_best_model = gsModel.best_estimator_
## 예측 진행
y_pre = gs_best_model.predict(newDF)

print(y_pre)

  sepal.length sepal.width petal.length petal.width
0         0.12        0.08         1.23        1.44
['Setosa']